global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: desafio-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - desafio-app:8080
