global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: desafio-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - desafio-app:8080
